theme: jekyll-theme-minimal
title: John Krijger
description: This my portfolio containing the major projects I did during my studies. My full curriculum vitae (in Dutch) can be found <a href="https://github.com/JohnKrijger/JohnKrijger.github.io/curriculum_vitae.pdf">here</a>.
