theme: jekyll-theme-minimal
title: John Krijger
description: This my portfolio containing the major projects I did during my studies. My full resume can be found <a href="https://JohnKrijger.github.io/curriculum_vitae_EN.pdf">here</a> and in <a href="https://JohnKrijger.github.io/curriculum_vitae.pdf">Dutch</a>.
