theme: jekyll-theme-minimal
title: John Krijger
description: This is my portfolio containing the major projects I did during my studies. <br> <br> <a href="https://JohnKrijger.github.io/curriculum_vitae_EN.pdf">View My Resume</a> <br> <br> <a href="https://JohnKrijger.github.io/curriculum_vitae.pdf">View My Dutch Resume</a>
